### PR TITLE
use HKL instead of unsigned int for keyboard layout in [keycode]

### PR DESCRIPTION
**Pull request by sebshader**

### CODE REVIEW

**Comment by Lucarda** [comment]
&#128077;

**Comment by porres** [comment]
so we're done, I need to warn people to not change layout after Pd is running in windows, huh?

**Comment by Lucarda** [comment]
it seems so :)

**Comment by porres** [comment]
cool

**Comment by sebshader** [comment]
well let's just say it seems like it.. it's tricky to test all keys and possibilities but issues will get tackled as they come up

**Comment by Lucarda** [comment]
this is just me: but there could also be an object `keyboard2midi` with this code. the only thing to change is the arrays to directly output MIDI notes.

**Comment by porres** [comment]
I am working on a [keymap] object that does it, try it

**Comment by sebshader** [comment]
@Lucarda personally I think it makes more design sense to have that in a separate object, to separate concerns.
all you really need is a [map] object that maps from specific numbers to other numbers, no need to re-do all the key handling stuff

**Comment by Lucarda** [comment]
>  need is a [map] object that maps from specific numbers to other numbers, no need to re-do all the key handling stuff

that also sounds good

**Comment by Lucarda** [comment]
> I am working on a [keymap] object that does it, try it

:) now it works!

**Pull request merged**
