### PR TITLE
Added jump on click, fixed setting expmode (hopefully), reorganised g…

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by porres** [comment]
seems we're almost there, but when  log is set in properties, you can't set it to any other non log value, either linear or exp... it stays locked in 'log' mode.

I can try and check it myself tomorrow or later

**Comment by porres** [comment]
Thanks to your comments on the tcltk code I was able to change a few things including the order of colors, really appreciate it :) thanks!

**Comment by porres** [comment]
fixed the issue where it was locked on log mode, it was on the C side, thanks again for all your help! Looks like we're finally done!

**Comment by porres** [comment]
not really done because we still need to fix the non jump on click behaviour in circular mode :( last thing on the list...

**Comment by porres** [comment]
In circular mode the knob jumps to your mouse position but it should not, unless in jump on click mode

**Comment by timothyschoen** [comment]
Do you think you can take care of this? I'm pretty busy for the rest of this week, and I'm not good at mouse behaviour and gui_vmess stuff in Pd.

**Comment by porres** [comment]
the main issue is the trigonometry math, I did not do the original thing and dont think I could do it... I have tried a few things to see if it would do it and it didnt... the mouse and vmess stuff is not the issue. I made it not jump but the mouse motion was kinda crazy and not really as I expected

**Comment by porres** [comment]
I can keep trying though but I'm also done for the week

**Comment by timothyschoen** [comment]
I think I fixed it, but please check :)

**Pull request merged**
