### PR TITLE
Update pd.lua

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by porres** [comment]
What's with this?

And can I get [circle]? :)

**Comment by porres** [comment]
hi, it seems some changes I had made were reverted, specially a copy of docs I had made...

I'll do things differently

**Comment by porres** [comment]
I'm getting this testing the graphics examples

**Comment by porres** [comment]
Screen Shot 2024-03-05 at 16 45 12

**Comment by porres** [comment]
For now, I made things just way too clear and simple, bascially removed the documentation, so we can add and do things later... I'm just saying this is a modified version with out [pdlua]/[pdluax] objects.

so, just waiting for [cicle] and we can get on with it, I could wait for scope3d~ later as that may be more complex to finish... so it's basically ready here on my end... we just need to see what's wrong and why I can't actually load graphics from your last PR

**Comment by timothyschoen** [comment]
> For now, I made things just way too clear and simple, bascially removed the documentation, so we can add and do things later... I'm just saying this is a modified version with out [pdlua]/[pdluax] objects.
> 
> so, just waiting for [cicle] and we can get on with it, I could wait for scope3d~ later as that may be more complex to finish... so it's basically ready here on my end... we just need to see what's wrong and why I can't actually load graphics from your last PR

It looks like you didn't update the scope3d object with my changes from the last PR:

- ```g.``` needs to be repaced with ```g:```
- ```path.start(x, y)``` needs to be replaced with ```Path(x, y)```

This error indicates it's calling ```g.set_color``` instead of ```g:set_color```. Both can be solved by simple seach-and-replacing

**Comment by porres** [comment]
ok, not sure what happened but things seem to work now. I am not really copying the tutorial or doing much... I dont wanna copy the whole documentation and tutorial for now... I'd like to have a separate documentation. But I do tell people to look for pdlua docs in the meantime, what do you think?

**Pull request merged**
