### PR TITLE
Fixes for [note]

### PR DESCRIPTION
**Pull request by timothyschoen**
Fixes all the current issues with note, except for undo support.

Also, there is still an issue with the outline: when you create a new [note] object, it initializes the value to 0, but the outline still shows.

### CODE REVIEW

**Comment by porres** [comment]
damn, it seems I never uploaded my latest version with the newly included "width" method. I uploaded it now! But setting it via properties doesn't work yet.

**Comment by porres** [comment]
> setting it via properties doesn't work yet.

took care of it

**Comment by porres** [comment]
> when you create a new [note] object, it initializes the value to 0, but the outline still shows.

not sure what you mean, I don't see any issues. The outline is always shown when in edit mode, that's all

**Comment by timothyschoen** [comment]
Aha, then the problem is that the outline does hide in edit mode, when you toggle it. Might be my fault though.

https://user-images.githubusercontent.com/44585538/190641668-b037f87c-0c07-4b5b-aeba-627a53ab4bc3.mov

**Comment by porres** [comment]
> then the problem is that the outline does hide in edit mode

I'll have a look at it, thanks

**Comment by porres** [comment]
> I'll have a look at it, thanks

fixed with 3b44152f6f7d6daaae9fddb51aa64d34db24c622

**Comment by porres** [comment]
> I'll have a look at it, thanks

fixed with 6f1cb293c1e42cc9ea6a6584953bace42454ab7c

**Pull request merged**
