### PR TITLE
[circuit~]

### PR DESCRIPTION
**Pull request by timothyschoen**
This is still a rough version, and the build system is not completed yet. It also needs more error checking, cleaning up, etc. But it does simulate circuits!

If you want to try it, run "make circuit" in ELSE's directory, and then the built external will appear in ./Code_source/Compiled/audio/circuit~/binaries/

### CODE REVIEW

**Comment by porres** [comment]
it built fine, give me example patches to try :)

**Comment by timothyschoen** [comment]
Here are some, you can paste these into a Pd object:


RC LOWPASS FILTER
```
circuit~;
voltage $s0 1 0;
resistor $s1 1 2;
capacitor 4.7e-08 2 0;
probe 2 0;
```

SIMPLE TRANSISTOR DISTORTION
```
circuit~;
voltage 12 1 0;
resistor 100000 2 1;
resistor 11000 2 0;
capacitor 1e-07 2 5;
resistor 1000 5 6;
input 6 0;
resistor 10000 1 3;
resistor 680 4 0;
bjt 2 3 4 0;
bjt 3 1 7 0;
resistor 100000 7 0;
probe 7 0;
```

MOOG OPAMP LOWPASS FILTER
```
circuit~;
probe 1 0;
voltage $s0 2 0;
opamp 3 4 1;
resistor 2300 4 1;
resistor 1000 4 0;
capacitor 0.000001 5 1;
capacitor 0.000001 3 0;
resistor $s1 2 5;
resistor $s1 5 3;
```

FUZZFACE
```
circuit~;
probe 1 0;
voltage $s0 2 0;
capacitor 2.2e-6 2 3;
resistor 100e3 3 4;
voltage 9 5 0;
resistor 330 5 6;
resistor 33e3 5 7;
resistor 8200 6 8;
capacitor 10e-9 6 9;
bjt 7 6 4 0;
bjt 3 7 0 0;
resistor 250e3 9 1;
resistor 250e3 1 0;
resistor 500 4 10;
resistor 500 10 0;
capacitor 20e-6 10 0;
```

VOX WAH
```
circuit~;
probe 1 0;
voltage $s0 2 0;
resistor 22e3 3 4;
bjt 5 7 6 0;
bjt 8 4 9 0;
resistor 470e3 4 10;
resistor 470 9 0;
resistor 1.5e3 8 11;
resistor 82e3 12 0;
resistor 68e3 2 13;
capacitor 1e-08 13 8;
voltage 9 3 0;
resistor 33e3 11 10;
capacitor 4.7e-6 10 0;
inductor 500e-3 11 10;
capacitor 0.01e-6 11 6;
capacitor 0.22 4 1;
capacitor 0.22 5 14;
resistor 1e3 3 7;
potmeter $s1 10e3 14 1 0;
resistor 10e3 6 0;
resistor 470e3 4 5;
```

**Comment by timothyschoen** [comment]
I'll also send patches soon, for the filters you need to know what kind of resistance you need to send in.

Be careful for your ears, sometimes there can be loud pops when turning on DSP. It's similar to switching on the power on a real analog circuit ;)

**Comment by timothyschoen** [comment]
Here is the start of a helpfile, with 2 examples

[circuit~-help-2.pd.zip](https://github.com/porres/pd-else/files/12541524/circuit.-help-2.pd.zip)

**Comment by porres** [comment]
fuzzface takes my 2013 macbook air to 1000% cpu usage

**Comment by timothyschoen** [comment]
> fuzzface takes my 2013 macbook air to 1000% cpu usage

Oh yeah I can imagine, it's about 40% on my 2020 MBP. You can try lowering the number of iterations with the "iter" message, to something much lower. This will reduce the quality (horrendously so below 5) but also improve performance. I'll see if I can get a few more optimisations in too. Did you try after my last PR? That should make a big difference.

I also have a Big Muff circuit but I think your laptop will explode then. My laptop does too.

**Comment by porres** [comment]
with the latest pr it got to 140%

**Pull request merged**
