### PR TITLE
Added -iter flag, improved helpfile, fixed issues with example circuits

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by timothyschoen** [comment]
I'm really convinced we're all done now :)

When do you think we can release it?

**Comment by porres** [comment]
> When do you think we can release it?

can you wait for 8.0.1? :) I already opened a new can of worms with new enigmas... trying to deal with MC oscillators now and delete the osc.mc~ as it became obsolete

**Comment by porres** [comment]
i'd aldo hope you'd help me a bit with some things, like finally getting the [bicoeff] gif more presentable

**Comment by timothyschoen** [comment]
> > When do you think we can release it?
> 
> can you wait for 8.0.1? :) I already opened a new can of worms with new enigmas... trying to deal with MC oscillators now and delete the osc.mc~ as it became obsolete

Oh yeah that's NP, just excited to get this out there :)

I can always include it in plugdata anyway, like an exclusive preview


> i'd aldo hope you'd help me a bit with some things, like finally getting the [bicoeff] gif more presentable

I might have time in a few weeks, but right now I'm way too busy as it is :(

I really didn't have time to make [circuit~], but I couldn't help myself, it was too much fun. I still have one small helpfile update coming up still, the current transistor amplifier circuit is garbage so I made a new one.

Also, I saw you added a "max gain" parameter, should I implement that? I think the preferred behaviour for me would be no limit, unless you pass the argument. If you're trying to build a square oscillator or distortion, the unasked for clipping could be confusing.

**Pull request merged**
