### PR TITLE
add support for ; \ and [ in messbox

### LINKED ISSUE #1036: messbox: escaped semicolon ( \; ) doesn't work with the set message
I can set a message with a comma by using "\," but "\;" doesn't work.

### PR DESCRIPTION
**Pull request by sebshader**
also take out x_selected
closes #1036

### CODE REVIEW

**Comment by porres** [comment]
works fine, but it'd be great if it could also break the line after ";"

while we're at it, I can't set a message with "\$" either, be it "\$0-x" or "$1-x", whatever

**Comment by porres** [comment]
I also realize typing "$0" or "\$0" into the box doesn't work. The first creates a '0' like pd's message boxes, the other seems to actually work, but creates a literal "$0" and doesn't expand, so I can't send data to "$0-f"

Screen Shot 2021-05-26 at 03 30 20

**Comment by sebshader** [comment]
yet another pr.. #1039

**Comment by porres** [comment]
> also take out x_selected

I think that screwed up the displacement of the handle
Screen Shot 2021-05-26 at 13 39 02

**Comment by sebshader** [comment]
@porres I can't reproduce this one. Do you have steps?

**Comment by sebshader** [comment]
@porres nevermind, I found it

**Comment by sebshader** [comment]
@porres is it that if you have multiple messboxes selected the handle moves on all of them? that bug already seems to have been present in the previous release of else

**Comment by sebshader** [comment]
@porres let me know if #1040 fixes the issues

**Comment by porres** [comment]
> let me know if #1040 fixes the issues

it all seems fine now ;) thanks!

**Pull request merged**
