### PR TITLE
Update help-files.pd through letter B

### PR DESCRIPTION
**Pull request by kreth608**
Also fixed a couple of typos and made capitalization uniform in the All_Objects.pd patch

### CODE REVIEW

**Comment by porres** [comment]
Hi, can't accept this, seems all files got ruined with a different window size.

Can you send me a PR just with the typo fixes?

Screen Shot 2022-08-28 at 14 40 24

**Comment by porres** [comment]
you can also open issues so we can discuss things before sending PRs

**Comment by porres** [comment]
sending small changes first into just a couple of files is also better  for us to start this process

**Comment by porres** [comment]
help file changes are really hard to compare looking at the code changes, you can also help by showing print screens to help describing what you changed

**Comment by porres** [comment]
> Can you send me a PR just with the typo fixes?

this should be easy to revise and merge just by looking at the changes

**Comment by kreth608** [comment]
Hi there, sorry to be unresponsive -- I'll try to PR just the typo changes soon

**Comment by kreth608** [comment]
> you can also open issues so we can discuss things before sending PRs
> sending small changes first into just a couple of files is also better for us to start this process

This is good to know, thanks for the feedback. I'm brand new to contributing, so I could use the guidance ;-)

**Pull request closed without merging**
