### PR TITLE
Further Messbox bugfixes/changes

### LINKED ISSUE #1020: [messbox] issues
- remove shift+click method
- add blue outline when selecting the object

### PR DESCRIPTION
**Pull request by sebshader**
Fixes a bug introduced in #1018 where the resizing handle wouldn't be deleted when re-opening a minimized window where the messbox was selected. Now the handle is drawn correctly (I don't think it was before that pr)

shift-click doesn't output from messbox anymore (though honestly I'm not sure why this should be taken out?)

the outline of messbox is blue when selected now.

Also fixes a bug where in edit mode if clicking on another object's text after having selected the messbox the text would be entered in both. However, in order to fix this bug now messbox must be clicked after moving it in order to enter text again (similar to the number box or symbol box objects)

I was not able to restore the previous text when the messbox is in a window that's minimized or in a subpatch that gets closed. This is due to pd not having a mechanism to notify tcl objects that a window is being closed at the moment. this would be possible after pure-data/pure-data#1323.

closes #1020

### CODE REVIEW

**Comment by porres** [comment]
THANKS!!!

> shift-click doesn't output from messbox anymore (though honestly I'm not sure why this should be taken out?)

doing that usually just uninteentionally selects some text in the object... for clicking and getting an output, better to conect a bang to it ;)

**Comment by porres** [comment]
@sebshader , it seems you have introduced a bug. Now messages with  a comma are not split into different messages anymor

**Comment by sebshader** [comment]
@porres huh I can't imagine what might have caused that, I'll look into it..

**Comment by sebshader** [comment]
@porres I cannot reproduce here. messages with commas are still output separately

**Comment by porres** [comment]
The example from the help file doesn't work for me, moreover, if I 'set' the message, it also outputs it (which it shouldn't) and it only outputs the first message. If I send it a bang or hit enter I only get '1' in the [print]

any other way i try it, by creating a new object and typing it and hitting enter also gives me the same.

Screen Shot 2021-05-25 at 20 44 07

**Comment by porres** [comment]
>  if I 'set' the message, it also outputs it (which it shouldn't if I 'set' the message, it also outputs it (which it shouldn't

forget about this, I have a 'bang' message afterwards

**Comment by porres** [comment]
hmmm, I seem to be getting this in the last release as well, and sometimes it does print all three messages...

but I tested this well before creating the object, so... I dunno what happened, and it is even weirder that it works for you. 

I guess I can create a new issue and maybe you can help me

**Comment by sebshader** [comment]
@porres hmm I still can't reproduce it only outputting the 1.. for me it out puts 1, 2 and 3 all separately if I press enter or click the bang

**Pull request merged**
