### PR TITLE
try fix windows

### PR DESCRIPTION
**Pull request by alcomposer**

### CODE REVIEW

**Comment by porres** [comment]
not ready yet, huh?

**Comment by porres** [comment]
good to go? tests went fine, right?

**Comment by alcomposer** [comment]
I think so. Linux failed but that looks like it was an internet dropout or something?
Tim or someone else may want to clean it up more. But it works for now.

Screenshot from 2023-08-22 02-02-39

**Comment by porres** [comment]
> I think so. Linux failed but that looks like it was an internet dropout or something?

usually @charlesneimog can tell us about this

**Comment by porres** [comment]
let's see how the new test goes

**Comment by charlesneimog** [comment]
Hi, in my machine, it is working, probably one simple bad request. In the actual build it is working again.

**Comment by porres** [comment]
I'm actually now unable to build, see error


-- Configuring done
CMake Error at cmake/PuredataConfig.cmake:68 (add_library):
  Cannot find source file:

    //elsefile.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  plugins/puredata/CMakeLists.txt:2 (include)


CMake Error at cmake/PuredataConfig.cmake:68 (add_library):
  No SOURCES given to target: elsefile
Call Stack (most recent call first):
  plugins/puredata/CMakeLists.txt:2 (include)

**Comment by porres** [comment]
It seems this is related to this https://github.com/porres/pd-else/issues/1774

sfz~ only loads if the elsfile object is loaded via some other object that actually loads it, in short, the linkage is still broken now for some reason @alcomposer

**Pull request merged**
