### PR TITLE
Added pdlua object, fixed some header issues

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by timothyschoen** [comment]
I see there were no git submodules in ELSE before. If you dislike having submodules, you can always delete them and copy the files in again. The advantage of submodules is that you get automatic updates.

**Comment by porres** [comment]
I have no idea really how to use submodules but I could compile stuff here just fine :) 

I had an error with "define _USE_MATH_DEFINES", seems you missed a "#", I fixed it.

**Comment by porres** [comment]
I couldn't really load pdlua though, I get 


_/Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin: dlopen(/Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin, 10): Symbol not found: _luaL_checklstring
  Referenced from: /Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin
  Expected in: flat namespace
 in /Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin
pdlua
... couldn't create_

**Comment by porres** [comment]
seems I will have to modify this a bit to get into ELSE, maybe use a different name (just [lua], as it's obvious it's lua in Pd once we are in Pd) and you know, mess with the help files, make it look like the other ones, etc...

**Comment by timothyschoen** [comment]
Yeah I agree. I think the compilation issue might be because of the missing submodule though, try running "git submodule init" in ELSE's directory.

**Comment by porres** [comment]
tried running "git submodule init" in ELSE's directory.

same error :) 


_/Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin: dlopen(/Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin, 10): Symbol not found: _luaL_checklstring
  Referenced from: /Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin
  Expected in: flat namespace
 in /Users/porres/Documents/Pd/externals/else/pdlua.pd_darwin
pdlua
... couldn't create_

**Comment by porres** [comment]
I think maybe some needed files haven't been copied

**Comment by porres** [comment]
> I think maybe some needed files haven't been copied

nope, copied them all, still no luck

**Comment by timothyschoen** [comment]
I see, made a small mistake. PR is coming!

**Comment by porres** [comment]
I am in fact having a hard time and troubles with the submodules.

Albert just accepted a PR and I wanted to update the submodule but I can't do it...

**Comment by porres** [comment]
> I am in fact having a hard time and troubles with the submodules.
> 
> Albert just accepted a PR and I wanted to update the submodule but I can't do it...

i'd like to learn, can you help? :) how is the whole thing being managed anyway? Both you and I have pdlua as a submodule?

**Comment by porres** [comment]
"Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>"

**Comment by porres** [comment]
Alexandres-MacBook-Air:pd-lua porres$ git pull upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Alexandres-MacBook-Air:pd-lua porres$ git pull origin
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

Alexandres-MacBook-Air:pd-lua porres$

**Comment by porres** [comment]
I may probably need to add other submodules later now that this beast grew out of control :)

**Pull request merged**
