### PR TITLE
fix crash on free

### PR DESCRIPTION
**Pull request by alcomposer**
add hdcc message
add multichannel flag -stout N

### CODE REVIEW

**Comment by porres** [comment]
please tell me more of what's going on here :)

**Comment by alcomposer** [comment]
Added hd-cc message: this allows to send a float value as a cc message, instead of 0-127, it's normalized 0.0-1.0

Added flag `-stouts` that allows sfz to set the number of stereo outputs. It is between 1 & 16. 

Fixed a memory issue when deleting sfz.

**Comment by porres** [comment]
I remember intentionally leaving 'hd-cc' and all the other 'hd' normalized versions out.

> Added flag -stouts that allows sfz to set the number of stereo outputs. It is between 1 & 16.

This is what I wanna know more about how it works, and if you meant you were using pd's multichannel feature

**Comment by porres** [comment]
no mc support I see... but it's something to think about. Tell me more about how this number of stereo channels work or should work. How do sfz files manage this kind of thing?

**Comment by alcomposer** [comment]
HDs make more sense from our use case, as PD is not locked to midi. Many values in SFZ can be extremely fine, so depending on the use case we should support it. And it's quite trivial to do so.

Yes, I'm not using the multichannel. This was to get it up and running. Would you prefer for it to be multi-channel? 

Sfz~ was not multi-channel with stereo, and the use case of multi-out would mainly be to directly apply effects / Futher processing to individual outs. 

Possibly it's better to allow the user to bind outputs as they see fit?

**Comment by alcomposer** [comment]
HDcc passes the float number directly to sfz, there is no conversion to 127.

SFZ only works in stereo pairs. You can not have 5 outputs. This is why I called the flag `-stouts` stereo outs.

**Comment by porres** [comment]
then it's the other way around, it divides by 127 in the normal way? I'd have to check back deep in there to make sure

**Comment by alcomposer** [comment]
MIDI cc is int 0-127. However there are many objects that accept 0-127 float in PD.

**Comment by porres** [comment]
my memory is from the original object I guess, or the one from ceammc... but yeah, I guess we can use the 0-127 range with float precision, and also other parameters

**Comment by porres** [comment]
hi, is this on your list?

**Comment by alcomposer** [comment]
What I'll do is do as we discussed and replace the cc with hdcc's that take 127 and normalize them.

I haven't got time to split this PR when I do it.

**Comment by alcomposer** [comment]
I can easily fix this up with what we discussed to be included here. That's no problem.

**Comment by porres** [comment]
already on it ;)

**Comment by porres** [comment]
cherry picked your 'fix crass on free'

allowed floar reolution for control values as well as velocity values, did not document this though and the same should be done for aftertouch, polyphonic aftertouch and maybe picth bend too? 

Now, can you please send me a PR for the 'multichannel' stuff? I would like to grab it and also work on allowing [sfz~] to output a single multichannel connection as well

**Pull request closed without merging**
