### PR TITLE
-midi

### PR DESCRIPTION
**Pull request by tomara-x**
:3

### CODE REVIEW

**Comment by porres** [comment]
@tomara-x I also added new messages/flags and changed things for plaits~ :/

netx time let's wait until it is actually released

**Comment by tomara-x** [comment]
hehe this is okay, anything for plaits ;)
i don't see any changes to flags though? just methods?

**Comment by tomara-x** [comment]
oh you have a -voct flag

**Comment by tomara-x** [comment]
oh i haven't opened the details subpatch before! i love how you made it like the two rows of led's! beautiful!

**Pull request merged**
