### PR TITLE
* fix elsefile include path in copied source file

### PR DESCRIPTION
**Pull request by alcomposer**
* add "set" method to load sfz file from string
* remove mention of soundfont in error messages

### CODE REVIEW

**Comment by porres** [comment]
actions failed and it still can't find the thing 
Screen Shot 2023-08-21 at 06 51 52

**Comment by porres** [comment]
fixed it

**Comment by alcomposer** [comment]
This isn't correct. Did you make clean beforehand? The sed script is replacing the include path when it copies the sfz~.c file.

**Comment by porres** [comment]
I can build it fine now but actions did fail for windows in https://github.com/porres/pd-else/actions/runs/5924745359 asking @Lucarda for help!

**Comment by porres** [comment]
and also @charlesneimog for help

**Comment by porres** [comment]
> This isn't correct. Did you make clean beforehand?

hmmm, not sure

**Comment by porres** [comment]
so i'm saying "yes" I had it cleaned

**Comment by porres** [comment]
ok, whatever was done in https://github.com/porres/pd-else/pull/1765 works for me, still waiting actions to finish

**Comment by Lucarda** [comment]
> asking @Lucarda for help!

I'm totally late for the party :)

I'm glad the thing is working but i must add that the initial intention[*] was to not touch anything on `sfizz` dir so that it could easily be updated to a newer version. but as long as this can be handled everything should be fine.

:)

[*] mainly because I don't really know `cmake`.

**Pull request merged**
