### PR TITLE
Remove pdlua

### PR DESCRIPTION
**Pull request by agraef**
As discussed previously (cf. https://github.com/porres/pd-else/issues/1477#issuecomment-1429119741). This completely removes pd-lua from ELSE, the rationale being:

- The two weren't such a great match in the first place, as ELSE isn't really about scripting a.k.a. 3rd-party language support. And Alex found that he isn't all that interested in pd-lua after all, as he admitted himself.
- It just complicates things in ELSE and means additional maintenance burden for @porres, when he should be concentrating on ELSE's core which, to be honest, is awesome enough by itself.
- It also makes it harder to integrate ELSE into Pd distributions which already have their own pd-lua module included from upstream.
- The only tangible benefit of including pd-lua with ELSE was that it provided a pathway to get pd-lua into Deken, but there are other ways to achieve that.

While I consider this move necessary and beneficial, I'd also like to stress that this doesn't take away anything from Alex' substantial contributions to improve the pd-lua help patches which I'm really happy about.

@timothyschoen, we'd love to hear your opinion on this. I know that you advocated for pd-lua to be included in ELSE, presumably because then you only have to worry about your bundled ELSE source rather than having to maintain a separate pd-lua submodule.

But I'd argue exactly the opposite, that including pd-lua in ELSE actually *adds* a lot of unnecessary friction and makes live more miserable for all of us. This already manifested itself in that ELSE included an old (and broken) pd-lua version until very recently, and the pd-lua update to fix this was severely botched. That was no doubt because Alex isn't very familiar with pd-lua, and I wouldn't expect him to be. Also, his decision to turn pd-lua from a submodule into bundled source only made it more difficult to update the pd-lua source in ELSE (hardships in dealing with git submodules notwithstanding, but these aren't all that difficult to master).

So IMHO the present proposal to remove pd-lua from ELSE in fact *reduces* the maintenance burden for all of us. Untangling pd-else and pd-lua will make it easier for us to advance our projects at our own paces and following our own release schedules. And it's not as if plugdata would loose anything from this move. Tim, I'll continue to send you PRs when there are notable pd-lua updates, and those will mostly be simple updates of submodule hashes, so there isn't a real maintenance burden for you there, just a click of the "merge" button. :)

We just have to remember that we also need to revert the pd-lua docs to the stuff from the pd-lua submodule in plugdata when plugdata updates its ELSE sources after this PR has been merged. But I can take care of that by submitting a PR to plugdata when the time comes.

### CODE REVIEW

**Comment by timothyschoen** [comment]
> @timothyschoen, we'd love to hear your opinion on this. I know that you advocated for pd-lua to be included in ELSE, presumably because then you only have to worry about your bundled ELSE source rather than having to maintain a separate pd-lua submodule.

I don't feel that strongly about that, might be better to remove it from ELSE.

**Comment by agraef** [comment]
Rebased on current master.

Ok, Alexandre, then let's just go ahead with this. I'll test this branch in a purr-data+else build using my CI just to make sure. But if you don't hear anything bad from me in the next 90 min then this should be ready to go in.

**Comment by agraef** [comment]
CI is [running](https://github.com/agraef/purr-data/actions/runs/4177371033).

**Comment by agraef** [comment]
All good, ready to go in!

**Comment by agraef** [comment]
Waiting for "Alex on the beach" to grab his smartphone and push the merge button. :))

**Comment by agraef** [comment]
@porres, climb down from the surfboard and stop kissing that young lady on your side. Your phone rings, it's merge time, push that button! :stuck_out_tongue_winking_eye:

**Comment by agraef** [comment]
Anyway, @porres, please don't forget to merge this before you roll the rc7 release. Thanks!

**Comment by porres** [comment]
> (I'm wondering, is Valentine's Day a thing in Brazil?)

we have our own different date in july, but capitalists are trying to create this other international one... as if one wasn't enough...

Two things: I'd really like us to coordinate then getting this in deken for at least all platforms I offer in ELSE.

Another thing: I have my own silly rule of ALWAYS shipping an update with a greater number of objects, so by removing a couple of one now (pdlua/pdluax) I had to come up with 2 replacements, and I did it, 1st one is an 'aubio' object that was just sitting here, so I just included "beat~" (for beat detection), but somehow it failed. Another one I finished today I am really excited about is "plaits~", which ports the "Plaits" module from Mutable Instruments, see --> https://github.com/porres/pd-plaits

can you guys please help me integrating these two into my repository so I can ship it in the next update along with this removal? If I do this, people won't be bummed out I took it out. I also asked around btw and people didn't really seem to bother :)

**Comment by agraef** [comment]
> Two things: I'd really like us to coordinate then getting this in deken for at least all platforms I offer in ELSE.

Well, I have no idea how to submit something to Deken, but I'm willing to give it a go if someone (that's you or someone else knowledgeable about Deken) talks me through the steps. And I literally mean talk, because I can't be bothered to read more than a single screen page of documentation about this, I'm just that impatient and have better things to do. :))

Other than that, I could maybe help you out with some pre-built binaries, though.

> Another thing: I have my own silly rule of ALWAYS shipping an update with a greater number of objects

That's a *really* silly rule, especially if you can't even figure out how to solve a simple Makefile issue by yourself. ;-)

> can you guys please help me integrating these two into my repository 

There you go: #1505. Come on, that was really easy, couldn't you have done this yourself?

**Comment by agraef** [comment]
> we have our own different date in july, but capitalists are trying to create this other international one... as if one wasn't enough...

They will *never* have enough of these sale days, money talks. :)

**Comment by agraef** [comment]
Yeah, plaits is cool, I didn't know that this existed for Pd.

Looks like this isn't compiled at all atm, because you didn't add it to the Makefile. What's the issue?

**Comment by porres** [comment]
> Yeah, plaits is cool, I didn't know that it existed for Pd. Looks like this isn't compiled at all atm, because you didn't add it to the Makefile and there's no source for it either, just a help patch. What's the issue?

I added and everything like an hour ago, maybe you missed somehow, but it's there. Tried different things and all of them failed.

My knowledge is pretty limited and I try to make it clear but people still get surprised :)

**Comment by porres** [comment]
> I added code and everything like an hour ago

https://github.com/porres/pd-else/commit/eed6650aa9817d40df81a42f80bf95f41d2181b1

**Comment by agraef** [comment]
Well, last time I pulled your sources it wasn't there. Ok, so the plaits sources have appeared now, but there's no README, no compilation/installation instructions, no nothing but the sources. Sorry, I realize that having plaits would be cool, but I have no time to do the research. So why not add something "else" to fulfill your silly rule, something easy, until someone actually figures out how to build this thing?

**Comment by porres** [comment]
I can actually build it, but based on this https://github.com/porres/pd-plaits

so it doesn't seem too hard

I guess I can also try and use @emviveros' script to build it separately... but of course it'd make much more sense and all if it could be easily compiled alongside all the rest.

**Comment by porres** [comment]
> I can also try and use @emviveros' script to build it separately...

I'll have access to the computer with the script and VM next week after carnival to try

**Comment by agraef** [comment]
> I can actually build it, but based on this https://github.com/porres/pd-plaits

Yeah, that helped. :) So you just have to add those cflags in the ELSE Makefile, then it compiles. (The -DTEST is important, because otherwise the compile fails on the assembler code in one of the headers.)

~~~diff
diff --git a/Makefile b/Makefile
index e66c5a56..ea31ef1f 100644
--- a/Makefile
+++ b/Makefile
@@ -7,11 +7,9 @@
 lib.name = else
 
 aubioflags = -Ishared/aubio/src
+plaitsflags = -DTEST -Wno-unused-local-typedefs -I.
 
-cflags = -Ishared -DHAVE_STRUCT_TIMESPEC $(aubioflags)
-
-# ?????????????????????????
-# cflags = -DTEST -Wno-unused-local-typedefs -I./
+cflags = -Ishared -DHAVE_STRUCT_TIMESPEC $(aubioflags) $(plaitsflags)
 
 uname := $(shell uname -s)
~~~

But the external still doesn't load, on Linux at least:

~~~
/usr/lib/pd/extra/else/plaits~.pd_linux: /usr/lib/pd/tcl/../extra/else/plaits~.pd_linux: undefined symbol: _ZN6plaits5Voice4InitEPN6stmlib15BufferAllocatorE
~~~

There's a bunch of those, and  the c++ demangler tells me that the missing C++ symbol there is `plaits::Voice::Init(stmlib::BufferAllocator*)`, which is in plaits/dsp/voice.cc, which is included in $(plaits), so I don't understand why this symbol is missing. Maybe a missing #include somewhere?

So we probably lack some bit of information there. Is there anything potentially related to this in your build scripts? Does the separately built version actually load, or does it have the same issue?

Tim, did you get any further than me?

**Comment by agraef** [comment]
Could also be a linker issue. I don't see that Voice::Init() is being called anywhere, though.

**Comment by porres** [comment]
> Is there anything potentially related to this in your build scripts? 

For now I get a zillion compilation warnings I haven't looked through carefully, but the object loads fine. I'd like to have them cleaned up though.

And I load my compiled external just fine here on macOS

**Comment by porres** [comment]
> I'd like to have them cleaned up though.

I can't, because the warnings are from the original plaits code... I removed the only warning the plaits~.cc code was giving...

**Comment by porres** [comment]
> So you just have to add those cflags in the ELSE Makefile, then it compiles

tried it in  [955cb2e](https://github.com/porres/pd-else/commit/955cb2e39460676fa18679c11c8ea8f47d314659) but it fails...




I am getting

warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead
[-Wstdlibcxx-not-found]
In file included from plaits/dsp/engine/chord_engine.cc:29:
In file included from ./plaits/dsp/engine/chord_engine.h:34:
In file included from ./plaits/dsp/engine/engine.h:34:
In file included from ./stmlib/dsp/units.h:33:
./stmlib/dsp/dsp.h:34:10: fatal error: 'cmath' file not found
#include <cmath>
^~~~~~~

which seems weird as it's a 'c++' thing that should be found, right? I don't have the same issue if I build from https://github.com/porres/pd-plaits for some reason.

**Comment by agraef** [comment]
Correction: Voice::Init() is being called here (plaits~.cpp:221):

~~~cpp
    stmlib::BufferAllocator allocator(x->shared_buffer, sizeof(x->shared_buffer));
    x->voice.Init(&allocator);
~~~

**Comment by agraef** [comment]
Can't test on the Mac right now, but on Linux this works for me. What macOS version is that, and do you have the latest Xcode installed?

**Comment by agraef** [comment]
Other than that, try adding `-stdlib=libc++` to the cflags and see whether that helps. This should really only be used with the C++ source, though, but pd-lib-builder doesn't support passing class-specific cflags. :(

**Comment by agraef** [comment]
Maybe pd-lib-builder is not happy with mixed c and c++ sources? I'm grasping at straws. But another way to deal with the situation would be to build plaits~ in its own subdir, like sfont~.

**Comment by agraef** [comment]
Sorry, I'm running out of ideas and I don't have time to work on this right now.

**Comment by porres** [comment]
> Maybe pd-lib-builder is not happy with mixed c and c++ sources?

maybe... that's something that occured to me, I could investigate and ask

> But another way to deal with the situation would be to build plaits~ in its own subdir, like sfont~.

yeah, that's my worst case scenario :)

**Comment by porres** [comment]
I also assume it's impossible to turn the plaits~.cc file into a plain 'c' file somehow...

**Comment by agraef** [comment]
> I also assume it's impossible to turn the plaits~.cc file into a plain 'c' file somehow...

Indeed.

> yeah, that's my worst case scenario :)

That's not worst case, I've seen much worse things in my time. ;-) That should be really easy to set up, you just need to follow sfont's example.

Have to sign off now, good luck. :)

**Comment by porres** [comment]
> but on Linux this works for me

what works for you?

I'm using mojave on a quite old macbook air

trying:

cflags = -stdlib=libc++ -Ishared -DHAVE_STRUCT_TIMESPEC $(aubioflags) $(plaitsflags)

didnt work but I guess I did it wrong...

> Have to sign off now, good luck. :)

no worries, thanks for the help

**Comment by agraef** [comment]
One last thing before I go, class.sources should be renamed to plaits.class.sources I guess:

~~~diff
diff --git a/Makefile b/Makefile
index ea31ef1f..0f164fe8 100644
--- a/Makefile
+++ b/Makefile
@@ -49,7 +49,7 @@ plaits := stmlib/dsp/units.cc \
                  plaits/dsp/physical_modelling/string_voice.cc \
                  plaits/resources.cc
 
-class.sources = Classes/Source/plaits~.cpp $(plaits)
+plaits.class.sources = Classes/Source/plaits~.cpp $(plaits)
 
 # Lib:
 else.class.sources := Classes/Source/else.c
~~~

But the idea to just pull pd-plaits as a submodule (or copy it) and then just build it in a subdir like sfont~ seems *much* more sensible, and might help solve the issues, both yours and mine. I might have a go at this tomorrow, but no promises...

**Comment by porres** [comment]
> which seems weird as it's a 'c++' thing that should be found, right? I don't have the same issue if I build from https://github.com/porres/pd-plaits for some reason.

and the reason is that there seems to be a different Makefile.pdlibbuilder in pd-plaits...

**Comment by porres** [comment]
Yup, I forked pd-plaits and it had this pdlibbuilder version (0.5.1)

The one I have and use in ELSE is 0.6.0 

If I replace 0.5.1 by 0.6.0 I get the same error I was when trying to build with in ELSE, namely:

./stmlib/dsp/dsp.h:34:10: fatal error: 'cmath' file not found
#include
^~~~~~~

I guess first step would be to make it possible to build pd-plaits with the new pdlibbuilder version

**Comment by porres** [comment]
Ok, plaits~ is now here at https://github.com/porres/pd-else/tree/master/plaits~

with the 'old'/'different' pdlibbuilder file.

**Comment by agraef** [comment]
Very good! My gut tells me that this is the right thing(TM), just leave it alone and build it in its own subdir, a.k.a. never change a working system. :) I'll add the necessary rigmarole to the toplevel Makefile tomorrow.

**Comment by agraef** [comment]
That did it! plaits~ also loads fine on Linux now. plaits targets for the toplevel Makefile are in #1512 now, these work exactly like the sfont targets.

**Comment by agraef** [comment]
Well, putting this into my purr-data pd-else branch, this doesn't look so great any more. CI refuses to compile it on both Mac and Windows, for different reasons. (Tries to link for i386 on the Mac, WTF, so I need to fix the compiler flags there. Missing header on Windows, so there's probably missing some -I flag there as well.) So there's still some work to do. I'll look into it later tonight.

**Comment by agraef** [comment]
The problem on the Mac you probably didn't notice, because you're on an older macOS version which still compiles for 32 bit. But that doesn't work on Monterey (and later) any more, which is what the Mac runners on GH use.

**Comment by agraef** [comment]
This does it for me: #1515. Please check that it still compiles on your Mac, too. Note that I fixed up the wrong target architectures on the Mac in plaits' pdlibbuilder with those from else's pdlibbuilder, so that it doesn't try to cross-compile to i386 any more. (That should work for most purposes, if you use the toplevel plaits target. But since I left the plaits~ source itself as is, you can still build an old-style fat Intel binary if you want by compiling plaits~ manually in its own subdir.) I also fixed the Windows compile failure, works now as well.

**Pull request merged**
