### PR TITLE
remove debug, switch x/y rotate, fix rotatey

### PR DESCRIPTION
**Pull request by ben-wes**

### CODE REVIEW

**Comment by porres** [comment]
rotate is still wrong (y, x), not (x, y)

**Comment by ben-wes** [comment]
now I'm confused. maybe I didn't test properly. but wasn't the first argument supposed to rotate horizontally?

**Comment by porres** [comment]
it was

**Comment by ben-wes** [comment]
ah ... i guess the confusion stems from the flipped arguments in message `rotate $2 $1` in your help? (that was probably mine originally when the rotations were according to the axis)

**Pull request merged**
