### PR TITLE
add realizedollar for `$0` receivers and comment out clip

### PR DESCRIPTION
**Pull request by ben-wes**
first step after a while for getting scope3d~ ready ...

### CODE REVIEW

**Comment by porres** [comment]
and why no clip no more?

**Comment by ben-wes** [comment]
> and why no clip no more?

it's a huge pain performance-wise. the implementation is actually checking for every line whether it crosses the boundaries - and in that case shortens it accordingly. and since we discussed performance-stuff, i'd strongly suggest not to add a feature that makes things even slower.

**Comment by porres** [comment]
is there a way to make it more efficient?

**Comment by porres** [comment]
I'm movint scope3d~ to a 'not yet' folder as I want to make a final release today or so as I can't hold it anymore :)

**Comment by ben-wes** [comment]
> is there a way to make it more efficient?

not for vanilla. and for plugdata, it gets automatically clipped anyway.



> I'm movint scope3d~ to a 'not yet' folder as I want to make a final release today or so as I can't hold it anymore :)

sure, go ahead! no problem from my side at all! there are no other pd-lua objects in else at the moment, right?

**Comment by porres** [comment]
> for plugdata, it gets automatically clipped anyway.

**Comment by porres** [comment]
> for plugdata, it gets automatically clipped anyway.

why?

**Comment by porres** [comment]
> there are no other pd-lua objects in else at the moment, right?

else/circle uses it, so I am shipping whatever the modified version I have right now... but I know new things are coming anyway

**Comment by porres** [comment]
> but I know new things are coming anyway

I mean new pdlua versions

**Comment by ben-wes** [comment]
> why?

because it handles drawing quite different.

> else/circle uses it

i was asking because of the issue with instantiating `else/scope3d~` ... does it work with `else/circle`?

**Comment by porres** [comment]
else/circle is a pd file abstraction, and it uses graphics internally. it's not a full blast coded in lua only object ;)

**Pull request merged**
