### PR TITLE
Use fluidlite instead of fluidsynth, for easier compilation

### PR DESCRIPTION
**Pull request by timothyschoen**
I leave it up to you if you want this, it has a few drawbacks.

- Some sf3 files that use obscure formats internally may not work. I've never encountered this in the real world, because why would anyone do that!
- Printing preset info doesn't work yet

The advantage is that it has a super simple build system with no external dependencies. I've been using this for years in plugdata without any problems, and without breaking compilation ever. It also gets rid of all the pre-built libs you have in the sfont folder.

It may be possible to bring preset info dump back, though I'm not sure how.

### CODE REVIEW

**Comment by timothyschoen** [comment]
OK, this now actually compiles sfont~ in the actions, for each platform

**Comment by porres** [comment]
> It may be possible to bring preset info dump back, though I'm not sure how.

I'm really fond of being able to do this :/

**Comment by timothyschoen** [comment]
OK, I've accidentally put the compilation fix for play.file~ into this branch

**Comment by timothyschoen** [comment]
Also implemented preset printing for [sfont~], so this should be ready for merge!

**Comment by porres** [comment]
you're the best, let me try this!

**Pull request merged**
