### PR TITLE
fixes for rotation and receive

### PR DESCRIPTION
**Pull request by ben-wes**

### CODE REVIEW

**Comment by porres** [comment]
you should not bind to empty, but you should have a logic that when it is set to 'empty' then it doesn't get any message... and thanks for catching the bug in [knob], this was a hard bug to find with these 2 objects acting weird :)

**Comment by ben-wes** [comment]
happy I found it. and funny that we had an issue in both objects! :)

afk for a bit now. but will check everything later! I think, rotatex and rotatey still need to be switched?

**Comment by porres** [comment]
I'm getting many debug prints, please clean it up

**Comment by porres** [comment]
> rotatex and rotatey still need to be switched?

they haven't been switched in 'rotate' and rotatex is fucked up now :)

**Pull request merged**
