### PR TITLE
Big optimisation for [circuit~]

### PR DESCRIPTION
**Pull request by timothyschoen**
I made a small mistake. This more than halved CPU use for me.

### CODE REVIEW

**Comment by timothyschoen** [comment]
In the last commit I changed the argument order of the BJT object. So some circuits have changed:

SIMPLE TRANSISTOR DISTORTION
```
circuit~;
voltage 12 1 0;
resistor 100000 2 1;
resistor 11000 2 0;
capacitor 1e-07 2 5;
resistor 1000 5 6;
input 6 0;
resistor 10000 1 3;
resistor 680 4 0;
bjt 0 2 3 4;
bjt 0 3 1 7;
resistor 100000 7 0;
probe 7 0;
```

FUZZFACE
```
circuit~;
probe 1 0;
voltage $s0 2 0;
capacitor 2.2e-6 2 3;
resistor 100e3 3 4;
voltage 9 5 0;
resistor 330 5 6;
resistor 33e3 5 7;
resistor 8200 6 8;
capacitor 10e-9 6 9;
bjt 0 7 6 4;
bjt 0 3 7 0;
resistor 250e3 9 1;
resistor 250e3 1 0;
resistor 500 4 10;
resistor 500 10 0;
capacitor 20e-6 10 0;
```

VOX WAH
```
circuit~;
probe 1 0;
voltage $s0 2 0;
resistor 22e3 3 4;
bjt 0 5 7 6;
bjt 0 8 4 9;
resistor 470e3 4 10;
resistor 470 9 0;
resistor 1.5e3 8 11;
resistor 82e3 12 0;
resistor 68e3 2 13;
capacitor 1e-08 13 8;
voltage 9 3 0;
resistor 33e3 11 10;
capacitor 4.7e-6 10 0;
inductor 500e-3 11 10;
capacitor 0.01e-6 11 6;
capacitor 0.22 4 1;
capacitor 0.22 5 14;
resistor 1e3 3 7;
potmeter $s1 10e3 14 1 0;
resistor 10e3 6 0;
resistor 470e3 4 5;
```

**Comment by timothyschoen** [comment]
All that needs to be done now is clear error messages if the circuit format is wrong.

**Comment by porres** [comment]
fuzzface down to 60% in my old fucked up laptop

**Comment by porres** [comment]
send a help file with more examples, let me work on that too :)

**Comment by timothyschoen** [comment]
Here's the wah-wah patch, maybe my favourite. It has some nice saturation going on (you can hear it better with guitar input) that would be tricky to mimic with regular DSP. 

[wah.pd.zip](https://github.com/porres/pd-else/files/12547345/wah.pd.zip)


Here is the simple distortion patch:

[bjt.pd.zip](https://github.com/porres/pd-else/files/12547367/bjt.pd.zip)


And here is the simple RC filter patch:

[simple_rc.pd.zip](https://github.com/porres/pd-else/files/12547375/simple_rc.pd.zip)


Other than that, I have a Big Muff, but it's too heavy for anyone to run. But that was kind of expected:

Screenshot 2023-09-07 at 11 51 42


I'll design some more circuits later. I want an analog oscillator at least, and I'll look for some more pedals with simple circuitry.


(sorry for using scale~, old Max habits die hard)

**Pull request merged**
