### PR TITLE
fixes for grid and min rate

### PR DESCRIPTION
**Pull request by ben-wes**
min rate was not restricted - went crazy with delay of 0.
grid wasn't properly clipped for clip:1

### CODE REVIEW

**Comment by porres** [comment]
issues I reported are exactly the same 

Screen Shot 2024-03-17 at 11 44 34


there is this error when adjusting dimensions and the plot does not adjust to the dimensions anymore and get clipped

**Comment by porres** [comment]
the rotation seems better now, rotatex rotatres horizontally, but counter clock wise if look from above and that doesn't seem right at all to me, cause I am dragging to the right I want to see it rotate in the same direction. maybe y is reversed too...

rotate message still has x/y reversed...

 but I also get "scope3d~: no method for 'float'" when adjusting it

still seems CPU heavy as GUI freezes

**Comment by porres** [comment]
just fixed 'rotate'

**Comment by ben-wes** [comment]
can you push the fix?

i'm trying to find out where that error message comes from. when i test `dim` here with new scope, it's all good. totally weird ...

**Comment by porres** [comment]
my fix fucked with rotatex, so I don't know what is going on and reverted back, you fix this :)

**Comment by ben-wes** [comment]
FFUUUUUCCCKKK ... i found the problem and it's quite funny: scope currently defaults to a receiver named `empty` and obviously, your knobs are sending to `empty` by default. i fixed it for scope3d~ now and there's no receiver set at all. but i think, you should also fix your knobs to not send any messages by default. PR incoming ...

**Comment by ben-wes** [comment]
ok, about the rotation: which axis should i invert now? :)

**Comment by porres** [comment]
> i'm trying to find out where that error message comes from. when i test dim here with new scope, it's all good. totally weird ...

really weird you can't reproduce this... since you included 'flames' I guess, this started happening

performance is not doable here with 50ms refresh rate, still bad, it got worse with clipping I guess

It seems things were really ok and better before flames and clip :)

**Comment by porres** [comment]
> ok, about the rotation: which axis should i invert now? :)

rotate gets y and x, should be x and y

**Comment by ben-wes** [comment]
> It seems things were really ok and better before flames and clip :)

yeah ... it included many changes. but flames shouldn't really be the problem since the performance is dependant on `perform` and `paint` routines. i changed quite some stuff there. but with the last optimizations, it's faster for me. which patch are you testing with? the help itself?

**Comment by ben-wes** [comment]
can we make an issue for the open scope3d~ things? or use the other one? so that we don't discuss in the PRs?

**Comment by porres** [comment]
sure, let's go back to the issue, or even reboot it

**Pull request merged**
