### PR TITLE
md reference files from plugdata

### PR DESCRIPTION
**Pull request by tomara-x**
<3

### CODE REVIEW

**Comment by tomara-x** [comment]
i put them on the outside i hope that's okay

**Comment by porres** [comment]
maybe i'll create a new 'documentation' folder and put this inside with the help files.

you now need to delete 3 objcts and add 4 new ones for the next release :) can you figure it out?

**Comment by tomara-x** [comment]
oh lol i forgot to delete lua and canvas.name
wait i thought there was just plaits and beat, what's the other 2?

**Comment by porres** [comment]
https://github.com/porres/pd-else/wiki/Developments-currently-in-progress-for-the-next-release

**Comment by porres** [comment]
see other changes fromthe changelog that also need to be incorporated into the md files  please

**Comment by porres** [comment]
i can try and take of it later on for the next times

**Comment by tomara-x** [comment]
canvas.name was also very useful in making sends and receives that are local to subpatch btw ;)

**Comment by tomara-x** [comment]
> see other changes fromthe changelog that also need to be incorporated into the md files please

yeah i'm not sure whether to try doing those changes to the md files now or wait till we have the final new objects/help files in plugdata

but i'm actually glad you have a list of changes, this makes everything easier <3

**Comment by porres** [comment]
do it now :)

**Comment by tomara-x** [comment]
yeah i wanna have some fun with them tomorrow :3

**Pull request merged**
