### PR TITLE
Fix plaits~ compilation.

### PR DESCRIPTION
**Pull request by agraef**
cf. https://github.com/porres/pd-else/pull/1503#issuecomment-1434831805

### CODE REVIEW

**Comment by porres** [comment]
Hi, if I build with my regular _make install objectsdir=../_ command on the toplevel make file with pdlibbuilder, I don't build plaits~ I guess I need something special, like sfont~ needs, right? BTW, I never really tried compiling with [sfont~], sorry, it's vacation/summer time as you know and I've been also busy doing ELSE/Cyclone things. Since this new release seems ready to go I'd like to close the gates and try to see if I can compile it all and call it a release.

Now, if I go into the plaits~ directory, I can build it with the changes

**Comment by agraef** [comment]
It's all described in the updated README. Note that a relative objectsdir doesn't work for the subdir installs, so you *must* use an absolute path there now if you want to install sfont~ and/or plaits~ with the toplevel make. (Same goes for the pdincludedir if you need to set that.)

The TLDR is:

- `make all sfont plaits` to build everything. (Can be skipped if you run the command below afterwards, because the install targets also make sure that everything is built first.)
- `make install sfont-install plaits-install objectsdir=$(pwd)/..` to install everything in the parent directory. Don't skip the `$(pwd)`, or it won't work. Also, those trailing slashes aren't needed and actually may cause trouble on Windows in certain situations, cut that habit.

I should maybe send you another update of the README which also covers plaits~. Stay tuned.

**Comment by agraef** [comment]
There you go: #1516.

**Comment by porres** [comment]
awesome, works like a charm. Will see now how it may or may not work with the script provided by @emviveros in my VM

**Comment by porres** [comment]
ok, it seems I was able to edit and run the script by emviveros and it's going now... it should include plaits and sfont

BUT.......... I now see that the build I have done before here on the mac includes sfont~ exernal but it doesn't include the differently specified folders for each platform including the statically linked dependencies separately. Shouldn't it have done that?

**Comment by agraef** [comment]
I've not seen those scripts you're using on the VM, so I don't know how they're supposed to work and can't help you with this. You will have to ask emviveros for help. All I can tell you is that the Makefile targets I created do their job exactly as intended, if you use them correctly, as documented in the README.

**Pull request merged**
