### PR TITLE
Bring changes from pd-sfizz

### PR DESCRIPTION
**Pull request by Lucarda**
following from https://github.com/porres/pd-sfizz/issues/1#issuecomment-1624809485

### CODE REVIEW

**Comment by porres** [comment]
the size got much larger...

**Comment by porres** [comment]
Files changed 2,045  [Files changed 2,045](https://github.com/porres/pd-else/pull/1681/files)

**Comment by Lucarda** [comment]
you can do `make sfizz-clean` it will delete around 200MB from `pd-else/sfizz~/sfizz~/build` this folder is ignored by git so is not on the repo but in your machine with just all the `.o` and build stuff. if you clean it you'll have a slow build as you had the first time.

**Comment by porres** [comment]
I see

**Pull request merged**
