### PR TITLE
Hopefully fixes #1238, otherwise still an improvement

### LINKED ISSUE #1238: envgen~ crashes mac

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by porres** [comment]
Classes/Source/envgen~.c:267:23: error: too many arguments to function call,
      expected 1, have 2
        free(temp_at, sizeof(t_atom) * ac-nlines);
        ~~~~          ^~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by timothyschoen** [comment]
Huh I though I fixed that typo. You can just remove the "sizeof(t_atom) * ac-nlines" part and it should be okay.

**Comment by timothyschoen** [comment]
Btw, I'm not sure this will actually fix the crash you're experiencing, because the crash never happened for me. If this doesn't work, maybe we should just revert it to how it was, see if that works.

**Comment by porres** [comment]
can you send me a new PR?

**Comment by porres** [comment]
> we should just revert it to how it was, see if that works.

reverting works

**Comment by porres** [comment]
I was in a hurry, had to leave, but sat and tried it, it works now

**Comment by timothyschoen** [comment]
Ah I was just preparing the PR ;)

But nice, no crash anymore either?

**Pull request merged**
