### PR TITLE
Fixing github actions build

### PR DESCRIPTION
**Pull request by timothyschoen**
(please don't merge yet, I'm just opening a PR so I can see if github actions are working now)

### CODE REVIEW

**Comment by porres** [comment]
no luck yet, huh?

**Comment by timothyschoen** [comment]
> no luck yet, huh?

Nope, not really sure why it won't work on Windows....

Good news is that it does work on macOS, and should also work on Linux :)

**Comment by porres** [comment]
Still failing some checks...

and I don't know how to build this so I can test it :) 

Screenshot 2024-07-08 at 13 58 14

**Comment by timothyschoen** [comment]
Ah yes, either from the top level makefile, do:

```
make play.file
```

Or, from play.file~ folder:
```
make ffmpeg
make play.file~
```

(and set PDDIR of course)

**Pull request merged**
