### PR TITLE
better $0 support and put a newline when ; is set or appended in messbox

### PR DESCRIPTION
**Pull request by sebshader**
~~$0 still doesn't get escaped in the middle of a symbol from "set" or "append" because it's tricky to find-and-replace in c in order to put the right backslashes in. ~~it will work~~ in the beginning of a symbol though.~~
edit: I was able to just copy the strings and insert a backslash in the appropriate locations

when \\; is entered into "set" or "append" it will insert a newline as well now

~~other arguments such as $1, $2 etc. won't work, but~~ $0 will now get expanded to the right value (hopefully)
the resolution of these values is somewhat ambiguous; should they refer to positional elements of an incoming list, as message boxes do, or should they refer to the arguments of the containing canvas, as objects do? $0 seems to be for an object, but the description of messbox is "GUI message box"

### CODE REVIEW

**Comment by sebshader** [comment]
with the newest commit I added message-box style positional arguments: so $1 in messbox will correspond to the 1st element in the incoming list (or float or symbol), $2 will correspond to the 2nd etc.
only works with "list", "float", and "symbol" messages though.

**Comment by sebshader** [comment]
I might be able to put $ in the middle of symbols after all...

**Comment by porres** [comment]
If I set the message like that with "$1" and then try to use 'append' with a float, it crashes Pd! 

We need explicit list, float and symbol method just for using with '$1'/'$2' etc... right?

Screen Shot 2021-05-26 at 13 40 18

**Comment by porres** [comment]
'append 1' actually crashes in any case!!!

**Comment by porres** [comment]
> 'append 1' actually crashes in any case!!!

it's working with the last release (beta 40), so one of the last things broke this

**Comment by sebshader** [comment]
@porres ah dang, I actually caught that bug but only fixed it for "set" and forgot to for "append".

**Pull request merged**
