### PR TITLE
Fix a bunch of memory bugs

### PR DESCRIPTION
**Pull request by timothyschoen**
I think this should work, but could you verify if it still works correctly?

### CODE REVIEW

**Comment by timothyschoen** [comment]
(hold up, made a small mistake)

**Comment by porres** [comment]
> I think this should work, but could you verify if it still works correctly?

what exactly should I test?

**Comment by porres** [comment]
> what exactly should I test?

I tested loop mode in tabreader~ and it was fine!

**Comment by timothyschoen** [comment]
> > what exactly should I test?
> 
> I tested loop mode in tabreader~ and it was fine!

NIce, then I think it should be all good!

**Pull request merged**
