### PR TITLE
Add "dump_delta" to [midi]

### PR DESCRIPTION
**Pull request by Jonathhhan**
It works now. Would be better with a flag for "dump", but not sure how to do that.

### CODE REVIEW

**Comment by porres** [comment]
can you first merge the last state and then propose the change? I have a new change you're reverting back with this commit "the 'argn' logic in "new".

**Comment by Jonathhhan** [comment]
@porres I hope now its fine.

**Comment by Jonathhhan** [comment]
I am sorry, there is still a bug. But should be fixable...

**Comment by porres** [comment]
what is the bug?

**Comment by Jonathhhan** [comment]
@porres first time I used it after opening the patch everything works fine. From the second time on the lists are longer than expected and there is a consistency check error:
First time:
```
xs:  193 18
xs:  195 33
xs:  196 113
xs:  197 37
xs:  198 27
xs:  199 25
size: 1651
```
Second time:
```
xs:  193 18consistency check failed: atom_string
 18
xs:  195 33 0
xs:  196 113 127
xs:  197 37 100
xs:  198 27 100
xs:  199 25 69
size: 1651
```

**Comment by porres** [comment]
I can't follow what you did actually...

**Comment by Jonathhhan** [comment]
@porres I hope at least my idea is understandable...

**Comment by porres** [comment]
I understand what you want. I don't understand why you did what you did, how and why... and I don't know where the bug is

**Comment by Jonathhhan** [comment]
Why: I want to parse midi messages with delta times into the markov abstraction. 
How: I can send you the patch (or make a minimal example).
Somewhere in here is the bug:
```
static void midi_dump_delta(t_midi *x){
    t_midievent *ep = x->x_sequence;
    int nevents = x->x_nevents;
    while(nevents--){  // LATER rethink sysex continuation
        unsigned char *bp = ep->e_bytes;
        double dp = ep->e_delta;
        int size = strlen((char*) bp);
	t_atom at[size + 1];
	SETFLOAT(at, (t_float)dp);
	SETFLOAT(at + 1, (t_float)*bp);
	int i;
	for(i = 0, bp++; i < size -1 && *bp != MIDI_EOM; i++, bp++)
		SETFLOAT(at + i + 2, (t_float)*bp);
        outlet_list(((t_object *)x)->ob_outlet, &s_list, size, at);
	ep++;
    }
    outlet_
bang(x->x_bangout);
}
```

**Comment by porres** [comment]
sorry, hasn'r been able to concentrate on this before... as I see it, you say you still have a bug here, right? If so I can't merge and would have to reject. Since this is already kinda polluted and confusing, may I just ask for you to redo the pull request if it is actually ok so I can better revise it?

**Comment by Jonathhhan** [comment]
I guess its better to reject my kind of pulluted, confusing pull request and leave it Flößer like it is. I wont do another pull request, but my idea is quite clear, and maybe someone more experienced can implement it. Its also absolutely fine for me, if not.

**Pull request closed without merging**
