### PR TITLE
Proper error handling, updated dependencies, big cleanup

### PR DESCRIPTION
**Pull request by timothyschoen**
There is one breaking change in here:

Before, inlet values were defined from $s0 on, now they are from $s1. This is to be consistent with expr~ syntax. It will print a warning when you open patches with $s0 in them.

### CODE REVIEW

**Comment by timothyschoen** [comment]
Okay, I think this is basically done. I asked the people who created the matrix solver library to implement an extra feature for us that would optimise things even more. Unfortunately I'm not smart enough to do that myself.

**Comment by timothyschoen** [comment]
[tube_screamer.pd.zip](https://github.com/porres/pd-else/files/12551276/tube_screamer.pd.zip)

This is the first 2 stages of a tube screamer, but I think I messed it up a bit because the gain control does nothing. It does distort nonetheless

**Comment by porres** [comment]
please put all of these into a help file :)

**Comment by porres** [comment]
and create a help file, hahaha

**Pull request merged**
