### PR TITLE
Include and build sfizz~

### PR DESCRIPTION
**Pull request by Lucarda**
this PR includes almost all files from https://github.com/sfztools/sfizz-ui to the `else` repo. this is around **120MB** (consider before merge :).

example usages:

build:
`make sfizz`

install:
`make sfizz-install objectsdir=./out extension=m_amd64`

clean:
`make sfizz-clean`

### CODE REVIEW

**Comment by porres** [comment]
> this is around 120MB (consider before merge :).

too late, merged before seeing this, hahaha, well... whatever, I don't really care, I got space in my machine

**Comment by Lucarda** [comment]
now that im thinking `make sfizz-install` will not work on mac and linux. I need more work.

i'll have a PR soon.

**Comment by porres** [comment]
it did work for me though

**Comment by porres** [comment]
oh, maybe not the "install"?

**Comment by Lucarda** [comment]
don't test it it wont work. I already have a fix. making a PR...

**Comment by Lucarda** [comment]
done via #1680

**Comment by porres** [comment]
i dont understand what was wrong and how to test the new thing now

**Comment by Lucarda** [comment]
you can now do

`make sfizz-install objectsdir=./out extension=d_amd64`

this change the file extension and move all files to `objectsdir`

**Comment by porres** [comment]
ok, well, actually I am starting a new repository and I hope you can help me with some issues, let's move it there

**Comment by Lucarda** [comment]
sure, where?

**Comment by porres** [comment]
https://github.com/porres/pd-sfizz/issues/1

**Comment by Lucarda** [comment]
> https://github.com/porres/pd-sfizz/issues/1

404 error

**Comment by Lucarda** [comment]
besides the 404 page not found, why you decided to move it out of else?

is it for the files size?

we can make it a submodule if so.

**Comment by porres** [comment]
it is now public try again https://github.com/porres/pd-sfizz/issues/1

I'm not taking it out of else, just gonna work on in separately then "merge" it back to else when it is ready... I usually do this, I did it with the [knob] object, with [sfont~] and seems reasonable to me, do you mind?

**Pull request merged**
