### PR TITLE
adding the final plaits models to plaits~

### PR DESCRIPTION
**Pull request by tomara-x**
first draft. need to fix fm ops models not working

### CODE REVIEW

**Comment by tomara-x** [comment]
since it is a derivative work, and it runs in pd, we could've called it "bangs" that would've been cute :laughing:

**Comment by porres** [comment]
ops models?

**Comment by porres** [comment]
oh, fm, what's wrong with them?

**Comment by tomara-x** [comment]
3 of the new models are 2-voice, 6-operator fm (each of those 3 has 32 different presets) those are the only thing not working yet

my guess it's probably something because of allocation. this feels wrong, they need to be different i think

https://github.com/porres/pd-else/pull/1795/files#diff-0bd2d3b3772f4738bfa63d65c86610d8616ac220717087f876471d6108ba1b04R107

but that's an adventure for tomorrow-amy

**Comment by tomara-x** [comment]
they're described better here https://pichenettes.github.io/mutable-instruments-documentation/modules/plaits/firmware/

**Comment by porres** [comment]
what changes in the documentation? so we'll really have new modules?

**Comment by porres** [comment]
wow, checked the link, holly shit

**Comment by tomara-x** [comment]
heheh yeah it's gonna be a new row of models, just need some time to figure out the fm ones

here you get to see a crash too :laughing:

https://github.com/porres/pd-else/assets/86204514/2d638324-fc64-4115-9018-fc7fdd870825


don't worry i'll take care of the help file after i'm done with the cleaning

**Comment by porres** [comment]
amazing, can't wait to add the plaits module to the collection of modular inspired abstractions. It's gonna be big

**Comment by porres** [comment]
i've ruined your PR, hate me forever now, or restart :)

**Comment by tomara-x** [comment]
don't worry, i'm a big girl, i can handle it. but yeah, i'm no expert on these particular cases, but i think it's generally good practice to avoid changing files that others are working on, to avoid these sort of conflicts. and opening a draft pr is the way to tell people that you're working on something and it might take you a while

**Comment by porres** [comment]
yeah, sorry, I only realized after I did it :/

**Comment by tomara-x** [comment]
also it's rarely a good idea to move half your repo, just saying

**Comment by tomara-x** [comment]
so is that final? audio instead of signal? why? that's gonna fuck up some stuff in plugdata btw. are you sure you wanna commit to that? again, why? do you wanna revert it maybe?

**Comment by porres** [comment]
I have made major overhauls like this a few times from time to time. Biggest motivation is having things better organize that annoys me in my workflow. I never really knew how plugdata kept up with these by the way. I thought it just used whatever structure I had or something, like a submodule.

Now, quite recently I made huge changes and @timothyschoen liked it and said it now made it better and easier to use it as a submodule indeed... I don't really know how it works on your side over there, but it seemed to me it made things easier and I could mess around without worries.

Anyway, I haven't really settled with this last reorganized because there isn't a new release yet and I'm trying to get things over with next week the latest. So I did this minor change compared to my very last one because it organizes things even better for me, and I'm getting rid of things that aren't used (like the 'libpd' folder)

And, well, it's nice that control and audio are next to each other alphabetically and extra is on the bottom, that's just it. Moreover, that's actually how Cyclone is organized and I was actually inspired by that, and then I checked and saw I made it differently, and now I see this is actually better and I'm also trying to make both repositories more consistent and structured in the same way...

Anyway, I'd wait until I finish the release and then I'll try to stick with the way things end up. There's now an inconsistency that is annoying me. In Cyclone I'm calling "binaries" and in ELSE I'm calling "compiled". I'll try to make a decision on changing one or another.

**Comment by tomara-x** [comment]
yeah, but it's work. like, you have to update your makefile, tim has to update the cmake stuff in plugdata (and a script that packages the abstractions).. just feels better to pick something and stick to it

**Comment by tomara-x** [comment]
yep, looking sharp

https://github.com/porres/pd-else/assets/86204514/1393a571-2593-497f-9939-fa0b6ff1d5d1

**Comment by tomara-x** [comment]
i meant to do this in another branch, but i always `git branch` and forget to `git switch` xD

**Comment by porres** [comment]
great, we need to update the help file now, right?

**Comment by tomara-x** [comment]
hehe yeah, leave that to me. i wanna give it the love it deserves :hearts:

**Comment by tomara-x** [comment]
btw, in case you want to play, here's a description (the orange ones)
https://drive.google.com/file/d/16VGibJgQ9SlxVPtzf2Ln_RW0WqDNyuym/view

**Comment by porres** [comment]
nice, but working on sfz~ now

**Comment by tomara-x** [comment]
nice! have fun <3

**Comment by porres** [comment]
I wonder how we can import DX7 files...

**Comment by tomara-x** [comment]
see this is one of the banks of patches loaded by default (this has 32 presets)

https://github.com/porres/pd-else/blob/b45a9adffb9e8f27769d99ce2ce0674820956f5c/Code_source/Compiled/audio/plaits~/plaits/resources.cc#L37

the three of them are added together here

https://github.com/porres/pd-else/blob/b45a9adffb9e8f27769d99ce2ce0674820956f5c/Code_source/Compiled/audio/plaits~/plaits/resources.cc#L3117

and then when we switch to one of those engines we load the corresponding bank

https://github.com/porres/pd-else/blob/b45a9adffb9e8f27769d99ce2ce0674820956f5c/Code_source/Compiled/audio/plaits~/plaits/dsp/voice.cc#L175

and the LoadUserData function in the engine handles the rest 

https://github.com/porres/pd-else/blob/b45a9adffb9e8f27769d99ce2ce0674820956f5c/Code_source/Compiled/audio/plaits~/plaits/dsp/engine2/six_op_engine.cc#L94

also look at the original plaits logic that i had to edit a little cause we don't use any actual user data (yet)

https://github.com/pichenettes/eurorack/blob/08460a69a7e1f7a81c5a2abcc7189c9a6b7208d4/plaits/dsp/voice.cc#L130

so the part i don't know anything about is how you can read dx7 files as an array like that, after that it's just a matter of calling LoadUserData on it and resetting the engine just like in voice.cc

**Comment by tomara-x** [comment]
also this https://github.com/porres/pd-else/blob/master/Code_source/Compiled/audio/plaits~/plaits/dsp/fm/patch.h

**Pull request merged**
