### PR TITLE
Fix Linux build

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by timothyschoen** [comment]
again here for the actions, don't close it yet :)

**Comment by timothyschoen** [comment]
yay!

**Comment by timothyschoen** [comment]
It's actually getting close now, what needs to be done is:

- [ ] Check if "set" message works correctly now (I think it does)
- [ ] Add "click to open file browser" behaviour like original play.file~
- [ ] Update helpfile:
  - Document file format support
  - Document "seek" and "speed" messages
  
  I think that's all! Could you take a look at these last things?

**Comment by porres** [comment]
I don't think we need a "click to open file browser" behaviour like original play.file~ since this is a compiled object, not an abstraction

**Pull request merged**
