### PR TITLE
flip x/y rotation in help message (slider2d)

### PR DESCRIPTION
**Pull request by ben-wes**

### CODE REVIEW

**Comment by ben-wes** [comment]
now we need the dollarg expansion ... do you know how to approach this? i would give it a try in pdlua maybe - but not sure how. possibly a method that's available in the pdlua context?
... so basically the unexpanded versions would need to be persisted (in the state especially) and would need to be expanded on initialization? but that should be managed by the pd lua object itself then?

**Comment by porres** [comment]
i dont get there is nothing wrong with slider2d, it does output a list of x/y

**Comment by porres** [comment]
oh...

**Comment by porres** [comment]
I still see a very bad performance and it's clipping when adjusting size, not adapting as before

rotation with the mouse and via messages are not consistent either

**Comment by porres** [comment]
if I click and drag up, it goes as intuitively expected, but with the rotate and rotatey it goes to the opposite direction

i think x could also be reversed for the 2 cases (drag and message)

**Comment by ben-wes** [comment]
> I still see a very bad performance 

hmm ... i seriously tested this to compare. i used the "pre-flames" version from https://github.com/ben-wes/pd-else/blob/646ffadac69ce7fb39fbc21610d347080d1a31e2/Code_source/Compiled/audio/scope3d%7E.pd_lua to compare to the current one. see screenshots and cpu usage. for me, the current version uses 25% less cpu.

Screenshot 2024-03-18 at 07 30 20
Screenshot 2024-03-18 at 07 31 02

**Comment by ben-wes** [comment]
> it's clipping when adjusting size, not adapting as before

not sure what you mean. what is clipping? you mean that the graph is drawn outside the bounds?

> rotation with the mouse and via messages are not consistent either

ah ... i see now that there were some inconsistencies. damn. with the next pr, the rotation with slider2d equals the mousedrag on the object. is that correct? otherwise, i really don't know what to change! :)

**Pull request merged**
