### PR TITLE
Fixed dialog problems

### PR DESCRIPTION
**Pull request by timothyschoen**

### CODE REVIEW

**Comment by timothyschoen** [comment]
shit i messed up

**Comment by timothyschoen** [comment]
oh no

**Comment by timothyschoen** [comment]
I think it's just the ramp_time bit you changed in your last commit that got messed up, so it's not too bad

**Comment by porres** [comment]
I fixed it, hold on... but I still get errors :( 

can't read "var_elsegui_l2_f1_b0": no such variable
can't read "var_elsegui_l2_f1_b0": no such variable
    while executing
"eval concat $$var_elsegui_l2_f1_b0"
    (procedure "::dialog_numbox::choose_col_bkfrlb" line 9)
    invoked from within
"::dialog_numbox::choose_col_bkfrlb .gfxstub7ffd0fed1e10"
    invoked from within
".gfxstub7ffd0fed1e10.colors.sections.but invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .gfxstub7ffd0fed1e10.colors.sections.but"
    (command bound to event)

**Comment by timothyschoen** [comment]
That's very strange, I don't get those...

**Comment by porres** [comment]
> That's very strange, I don't get those...

let me test again

**Comment by porres** [comment]
yay, it's actually working :) and I have no idea of what's going on yet :( hahahahah

thanks so much

**Comment by porres** [comment]
Wow, for some reason, I cannot click and drag on the number box anymore. Pd freezes and explodes...

**Comment by timothyschoen** [comment]
In my experience this is usually a recursive loop

**Comment by porres** [comment]
yeah, but I didn't change any of that, I just accepted your changes for the dialog... weird

**Comment by porres** [comment]
Fixed the GUI freeze with https://github.com/porres/pd-else/commit/2716ecd5af3ccea3aec939464af6caf87ccdf147 

it was probably some variable names in the tcl/tk dialog that were wrong, don't ask me how and why though, probably with all the changes I was doing you just didn't keep up with it, sorry :(

**Pull request merged**
